### ISSUE TITLE
Specify BG color for each row of mode II patterns

### ISSUE THREAD

**Issue by visrealm** [mvac7/spriteSXdevtool#2]
Is there a way to specify different BG colors for each row in a mode 2 pattern? This is supported by the hardware.

**Comment by mvac7** [comment]
Hello Troy.

I don't know this property of the sprites that you mention.
I would appreciate it if you could show me some reference on this topic.

When designing SpriteSX, I have relied on the following information:
(although I did not include the status of EC and IC)

On the V9938 and higher, in sprite mode 2, color information must be written to the Sprite Color Table, for each of the 32 sprite planes.

It contains the colors of the 16 lines (or 8 depending on sprite size), along with the information bits to activate the horizontal offset (EC), sprite priority (CC) (also known as the OR bit) and the collision detection (IC).

Page 95 - V9938 MSX-VIDEO Technical Data Book - 2.6 Sprite Color Table (G3, G4, G5, G6, G7)
https://map.grauw.nl/resources/video/yamaha_v9938.pdf

**Comment by visrealm** [comment]
Ah. Sorry.

My use case was for Graphics Mode 2 tiles on a regular TMS9918A. I assumed, since you allow setting the foreground color for each row, which the TMS9918A doesn't support for sprites, that the tool was used for designing Mode 2 tiles which do support a different foreground and background color for each row.

**Comment by mvac7** [comment]
Don't worry.

This application was only designed for sprites.
I'm working on an app to draw tiles, but give a release date.
You can use nMSXtiles for that task:
https://github.com/pipagerardo/nMSXtiles

Thanks for your interest.

**Comment by visrealm** [comment]
Thanks.  Closed issue as this repo is for sprites only.
